version: "3.4"
services:
    op_challenge:
        container_name: op_challenge
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
         - /var/www/html/map:/app/html
        tty: true
        environment: 
         - LINE_ACCESS_TOKEN
         - LINE_SECRET_KEY
         - LINE_ACCESS_TOKEN_TEST
         - LINE_SECRET_KEY_TEST
         - OP_CHALLENGE_CONSUMER_KEY
