version: "3.4"
services:
    op_challenge:
        container_name: "${CONTAINER_NAME}"
        build:
            context: ./
            dockerfile: Dockerfile
        image: chatrain
        volumes:
         - /var/www/html:/app/html
        tty: true
        environment: 
         - LINE_ACCESS_TOKEN_TEST
         - LINE_SECRET_KEY_TEST
         - LINE_ACCESS_TOKEN
         - LINE_SECRET_KEY
         - OP_CHALLENGE_CONSUMER_KEY
