version: "3.4"
services:
    op_challenge:
        container_name: op_challenge
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
         - /var/www/html:/app/html
        tty: true
        environment:
         - LINE_ACCESS_TOKEN
         - LINE_SECRET_KEY
         - OP_CHALLENGE_CONSUMER_KEY
